LM/urls.py
"""
Lang_ar[4]=> 
from django.conf.urls.i18n import i18n_patterns
urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]
// += i18n_patterns
// رابط اللغة اساسي عشان كدة نخليه وحده
--------
[static & template]=>
from . import  settings
from django.contrib.staticfiles.urls import static
 + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
"""
from django.contrib import admin
from django.urls import path, include

from . import  settings
from django.contrib.staticfiles.urls import static

from django.conf.urls import handler404
from django.shortcuts import render

# from .views import handler_404

from django.conf.urls.i18n import i18n_patterns

def custom_404(request, exception):
    return render(request, '404.html', status=404)

handler404 = custom_404

urlpatterns = [
    path('i18n/', include('django.conf.urls.i18n')),
]

urlpatterns += i18n_patterns(
    path('admin/', admin.site.urls),
    path('', include('_pages.urls')),
    path('account/', include('_account.urls')),
    path('product/', include('_product.urls')),
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

_product/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    # 0 🔴 All Products Page:-
    # 0:A: All Products ✔️
    path('products', views.Products_List, name='Products_List'),
    # 0:B: ✔️(Json)
    path('load_more', views.Load_More,name='load_more'), # (json)


    # 2: filter Age ✔️
    path('age-filter/<str:age>/', views.Products_from_Link_age, name='Products_Links_age'),
    # 2: filter gender ✔️
    path('gender-filter/<str:gender>/', views.Products_from_Link_gender, name='Products_Links_gender'),
    # 2: filter category ✔️
    path('category-filter/<str:category_name>/', views.Products_from_Link_category, name='Products_Links_category'),
    # 2: filter best rate ✔️
    path('products/best_rate', views.bestRateProducts, name='best_rate_products'),
    # 2: filter new arrival ✔️
    path('products/new_arrival', views.newArrivalProducts, name='new_arrival_products'),
    
    # 3: search ✔️
    path('products/', views.searchProducts, name='search_products'),



    # 4: counts WishList and Cart ✔️ (product(s))
    path("wishlistCount", views.wishlist_count, name="wishlist_count"), # (json)    
    path("cartItemCount", views.cartItem_count, name="cartItem_count"), # (json)
    
    # 5: add or remove from WishList or Cart ✔️ (product(s))
    path("wishlist_ar", views.Add_or_remove_Wishlist, name="Add_or_remove_Wishlist"), # (json)
    path("single_cartItem_ar", views.Add_or_Remove_Single_CartItem, name="Add_or_Remove_Single_CartItem"), # (json)
    
    
    # 6: 🔴 single Product:-
    path('products/<int:pk>/', views.Product_Detail, name='Product_Detail'),

    path('products/<int:pk>/wishlist/', views.Add_or_remove_Wishlist_PD, name='wishlist_ar_pd'),

    path('products/<int:product_id>/add-to-cart/', views.add_to_cart_product, name='add_to_cart'),
    path('products/<int:product_id>/add-review/', views.add_review_product, name='add-review'),



    # cart and wishList 
    # 7: 🔴 WishList:-
    path('products/wishlist', views.wishlist, name='wishlist'),
    path('products/remove_Wishlist', views.remove_Wishlist, name="Add_or_remove_Wishlist"), # json
    path('products/wishlist_partial', views.wishlist_partial, name="wishlist_partial"), # json


    # 8: 🔴 Cart:-
    path('products/cart', views.cart, name='cart'),
    path('products/remove_cart', views.remove_cart, name='remove_cart'), # json
    path('products/cart/update-cart-item/', views.update_cart_item, name='update_cart_item'), # json
    # path('products/cart_partial', views.cart_partial, name="cart_partial"), # json

    # 9: 🔴 Order:-
    path('products/order_checkout', views.order_checkout, name='order_checkout'),
    path('products/order', views.order, name='order'),
    path('products/mark_received', views.mark_as_received, name='mark-received'),
]
'''
{% url 'Products_List' %}
{% url 'Product_Detail' %}
{% url 'wishlist' %}
{% url 'cart' %}
{% url 'wishlist' %}
{% url 'order' %}
'''

_product/models.py
from django.db import models
from _account.models import CustomUser, Customer
from django.db.models import Avg
from django.urls import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils import timezone

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True, verbose_name="اسم الفئة")

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name = "فئة"
        verbose_name_plural = "a_الفئات"

class SubCategory(models.Model):
    name = models.CharField(max_length=255, verbose_name="اسم الفئة الفرعية")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="الفئة الرئيسية")

    def __str__(self):
        return f"{self.name} ({self.category.name})"
    
    class Meta:
        verbose_name = "فئة فرعية"
        verbose_name_plural = "b_ الفئات الفرعية"

class Product(models.Model):
    choices_gender = [
        ('a', 'ذكر'),
        ('b', 'أنثى'),
        ('c', 'للجنسين')
    ]
    
    choices_colors = [
        ('#FF0000', 'أحمر'),
        ('#0000FF', 'أزرق'),
        ('#FFFF00', 'أصفر'),
        ('#00FF00', 'أخضر'),
        ('#FFA500', 'برتقالي'),
        ('#800080', 'بنفسجي'),
        ('#000000', 'أسود'),
        ('#FFFFFF', 'أبيض'),
        ('#808080', 'رمادي'),
        ('#A52A2A', 'بني'),
        ('#FFC0CB', 'وردي'),
        ('#F5F5DC', 'بيج')
    ]

    choices_age_range = [
        ('a', '1-3 أشهر'),
        ('b', '4-6 أشهر'),
        ('c', '7-9 أشهر'),
        ('d', 'سنة'),
    ]


    product_name = models.CharField(max_length=255, verbose_name="اسم المنتج")
    product_description = models.TextField(blank=True, null=True, verbose_name="وصف المنتج")
    product_image = models.ImageField(upload_to='ProductsImages/%Y/%m/%d/', verbose_name="صورة المنتج")
    product_purchas_cost = models.FloatField(verbose_name="سعر الشراء")
    product_selling_price = models.FloatField(verbose_name="سعر البيع")
    product_stock_quantity = models.IntegerField(verbose_name="الكمية في المخزون")
    product_subcategory = models.ForeignKey(SubCategory, on_delete=models.CASCADE, verbose_name="الفئة الفرعية")
    product_age_range = models.CharField(max_length=50, choices=choices_age_range, verbose_name="الفئة العمرية", default="a")
    product_gender = models.CharField(max_length=10, choices=choices_gender, verbose_name="الجنس", default="c")
    product_color = models.CharField(max_length=10, choices=choices_colors, verbose_name="اللون", default="#FFFFFF") 
    product_created_at = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الإنشاء")
    product_updated_at = models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث")
    product_is_active = models.BooleanField(default=True, verbose_name="متاح")

    def __str__(self):
        return self.product_name
    
    class Meta:
        verbose_name = "منتج"
        verbose_name_plural = "c_المنتجات"

    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"pk": self.pk})


    def get_absolute_url(self):
        return reverse("product_detail", kwargs={"pk": self.pk})

    def average_rating(self):
        avg_rating = Review.objects.filter(product=self).aggregate(Avg('rating'))['rating__avg']
        return round(avg_rating, 2) if avg_rating else 0  # إذا لم يكن هناك تقييمات، أعد 0

class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images', verbose_name="المنتج")
    image = models.ImageField(upload_to='ProductsImagesAdd/%Y/%m/%d/', verbose_name="الصورة")

    def __str__(self):
        return f"صورة لـ {self.product.product_name}"
    
    class Meta:
        verbose_name = "صورة منتج"
        verbose_name_plural = "d_صور المنتجات"

class Wishlist(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name="العميل")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="المنتج")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="التاريخ")

    class Meta:
        unique_together = ('customer', 'product')  # لمنع تكرار نفس المنتج لنفس العميل

    class Meta:
        verbose_name = "مفضل"
        verbose_name_plural = "e_المفضلة"

    def __str__(self):
        return f"{self.customer.user.email} - {self.product.product_name}"

class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, verbose_name="العميل")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="تاريخ الانشاء")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="تاريخ التعديل")
    is_active = models.BooleanField(default=True, verbose_name="نشط؟")
    class Meta:
        verbose_name = "السلة"
        verbose_name_plural = "f_السلال"

    def __str__(self):
        return f"{self.customer.user.email} -  {'نشطة' if self.is_active else 'غير نشطة'}"

class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE, verbose_name="السلة")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name="المنتج")
    quantity = models.PositiveIntegerField(verbose_name="الكمية")

    @property
    def total_price(self):
        return self.quantity * self.product.product_selling_price  # حساب السعر بدل تخزينه

    # total_price = models.PositiveIntegerField(verbose_name="السعر الاجمالي")
    class Meta:
        verbose_name = "عنصر السلة"
        verbose_name_plural = "f_عناصر السلة"

    def __str__(self):
        return f"{self.cart.customer.user.email} - {self.cart.created_at.date()} - {self.product.product_name}"

class Review(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE,  verbose_name="العميل")
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="reviews",  verbose_name="المنتج")  # إضافة related_name لتسهيل العلاقة
    created_at = models.DateTimeField(auto_now_add=True,  verbose_name="تاريح الانشاء")
    rating = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(5)],  verbose_name="التقييم النجمي")
    comment = models.TextField(blank=True, null=True,  verbose_name="التقييم النصي")

    class Meta:
        verbose_name = " مراجعة المنتج "
        verbose_name_plural = "g_مراجعات المنتجات"

    def __str__(self):
        return f"Review by {self.customer} for {self.product} - {self.rating} stars"

# Oreder Models:-

class Delivered(models.Model):
    name = models.CharField(max_length=255,  verbose_name="اسم عامل التوصيل")
    phone = models.CharField(max_length=20,  verbose_name="رقم الهاتف")
    address = models.TextField(verbose_name="العنوان")
    created_admin = models.ForeignKey(CustomUser, on_delete=models.SET_NULL, null=True,  verbose_name="تمت الاضافة من")
    created_at = models.DateTimeField(auto_now_add=True,  verbose_name="تاريخ الاضافة")

    class Meta:
        verbose_name = " الموصل  "
        verbose_name_plural = "h_الموصلين"


    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        current_user = kwargs.pop('current_user', None)

        if not self.pk and current_user:
            if not current_user.is_staff:  # أو current_user.is_superuser حسب نوع الأدمن عندك
                raise ValueError("فقط الإدمن يمكنه إضافة عامل توصيل.")
            self.created_admin = current_user

        super().save(*args, **kwargs)

class OrderCheckout(models.Model):
    code = models.CharField(max_length=30, unique=True, blank=True, verbose_name="كود السلة المنفرد")
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE, verbose_name="السلة")
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='orders', verbose_name="العميل")
    additional_description = models.TextField(null=True, blank=True, verbose_name="وصف اضافي للمنتج")
    value_bill = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="الفاتورة")
    received_price = models.DecimalField(max_digits=10, decimal_places=2, default=0, verbose_name="المبلغ المدفوع")

    choices_Payment_State = [

        ('p0', 'لم يتم التسليم'),
        ('p1', 'تم التسليم'),

        
    ]
    choices_Order_State = [
        ('o0', 'قيد الانتظار'),
        ('o1', 'جار المعالجة'),
        ('o2', 'تم الشحن'),
        ('o3', 'تم التسليم'),
        ('o4', 'تم الإلغاء'),
    ]
    choices_Received_State = [
        ('r0', 'لم يتم الاستلام'),
        ('r1', 'تم الاستلام'),
    ]

    # التحكم من : updated_by (admin) اي تسجل من قام بالتعدل
    payment_stats = models.CharField(max_length=2, choices=choices_Payment_State, default='p0', verbose_name="حالة الدفع") 
    # التحكم من : updated_by (admin) اي تسجل من قام بالتعدل
    order_stats = models.CharField(max_length=2, choices=choices_Order_State, default='o0', verbose_name="حالة الشحن")      
    # التحكم من : customer اي تسجل من قام بالتعدل
    received_stats = models.CharField(max_length=2, choices=choices_Received_State, default='r0', verbose_name="حالة الاستلام") 


    updated_by = models.ForeignKey(
        CustomUser, on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='updated_orders',
         verbose_name="قام بالتعديل:"
    )
    
    
    #  التحكم من : updated_by (admin) اي تسجل من قام بالتعدل لل : delivered_by
    delivered_by = models.ForeignKey(
        Delivered, on_delete=models.SET_NULL,
        null=True, blank=True,
        related_name='delivered_orders',
         verbose_name="عامل التوصيل"
    )

    def save(self, *args, **kwargs):
        # من نفّذ هذا التعديل؟ يجب تمرير المستخدم كـ kwarg
        current_user = kwargs.pop('current_user', None)

        # إذا الكود مش موجود، ننشئ كود فريد
        if not self.code:
            now = timezone.now()
            year = now.strftime('%Y')
            day = now.strftime('%m%d')
            prefix = f'ORD-{year}-{day}'
            last_order = OrderCheckout.objects.filter(code__startswith=prefix).order_by('-id').first()

templates/product/cart.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Cart {% endblock %} 

{% block content %}
    <section class="cart-wishlist-section">
        <div class="container mt-3 mb-5">
            <div class="d-flex gap-2 justify-content-between align-items-center">
                <h2 class="text-center text-secondary"> مقتنياتك المميزة </h2>
            </div>
            <div class="row mt-4">
                {% if cart_items %}
                    <!-- يوجد منتجات -->
                    <div class="col-md-8 ">
                        <div class="card">
                            <div id="cart-items">
                                <!-- star looop -->
                                {% include "product/cart_items.html" %}
                                <!-- end looop -->
                            </div>
                        </div>
                    </div>
                    
                    <form class="col-md-4">
                        {% csrf_token %}
                        <div class="card" style="background: transparent;">
                            <div class="mt-4">
                                <span>عدد المنتجات: <br><strong id="total-items" class="fs-4">  {{total_items}}  
    
                                </strong> منتجات </span><br>
                                <span class="total-price ">المجموع: <br>
                                    <!-- -->
                                    <strong id="total-price-text" class="fs-4">0</strong> 
                                    ريال يمني
                                    <input type="number" name="" id="total-price" class="fs-4" disabled hidden style="display: none;">
                                </span>
                            </div>
                            <div class="mt-3">
                                <div class="mb-4 mt-4 title">
                                    هل لديك تفاصيل لطلبك؟
                                </div>
                                <div class="mb-3">
                                    <textarea class="form-control" id="addDicTextarea" name="new-faqs" rows="3"
                                        placeholder="اكتب هنا"> </textarea>
                                </div>
                            </div>
                            <button class="btn-primary-one text-center checkout-btn" id="#checkout-btn"> طلب </button>
                        </div>
                    </form>
                {% else %}
                    <span class="d-flex flex-column justify-content-center align-items-center">
                        <h2 class="title-empty">
                            لا توجد منتجات 
                        </h2>
                        <a class="btn-primary-tow" href="{% url 'Products_List' %}"> استمر بالتسوق </a>
                    </span>
                {% endif %}
            </div>
        </div>
    </section>

    

    {% include 'product/suggestionsProduct.html' %}

{% endblock %}





{% block javascript %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            rate_conflict();
            {% comment %} function updateTotal() {
                let total = 0;
                $(".cart-item").each(function () {
                    let quantity = parseInt($(this).find(".quantity").val());
                    let unitPrice = parseInt($(this).find(".price-product-total").data("price"));
                    let totalItemPrice = quantity * unitPrice;
                    $(this).find(".price-product-total").text(totalItemPrice + " ريال");
                    total += totalItemPrice;
                });
                $("#total-price").val(total);
            } {% endcomment %}

            function updateCartTotalPrice() {
                let totalQuantity = 0;
            
                $(".cart-item").each(function () {
                    let totalPrice = parseInt($(this).find(".totalPrice").val());
                    if (!isNaN(totalPrice)) {
                        totalQuantity += totalPrice;
                    }
                });
            
                {% comment %} $("#total-price").text(totalQuantity + " قطع"); {% endcomment %}
                $("#total-price").val(totalQuantity);
            }
            updateCartTotalPrice();

            function saveQuantityToServer(itemId, quantity) {
                let updateUrl = "{% url 'update_cart_item' %}";
                $.ajax({
                    url: updateUrl, 
                    method: "POST",
                    data: {
                        item_id: itemId,
                        quantity: quantity,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                    },
                    success: function (response) {
                        console.log("تم تحديث الكمية");
                    },
                    error: function (xhr) {
                        console.log("فشل التحديث");
                    }
                });
            }
            
            function updateTotal() {
                let total = 0;
            
                $(".cart-item").each(function () {
                    let quantity = parseInt($(this).find(".quantity").val());
                    let unitPrice = parseInt($(this).find(".price-product-total").data("price"));
                    let totalItemPrice = quantity * unitPrice;
                console.log("الكمية:", quantity, "السعر:", unitPrice, "المجموع الجزئي:", totalItemPrice);

            
                    // تحديث السعر المعروض
                    $(this).find(".price-product-total").text(totalItemPrice + " ريال");
                    // جمع المجموع الكلي
                    total += totalItemPrice;
            
                    // حفظ الكمية في السيرفر
                    let itemId = $(this).data("product-id");  // تأكد عندك data-item-id في div.cart-item
                    saveQuantityToServer(itemId, quantity);
                });
            
                $("#total-price-text").text(total);
                console.log($("#total-price-text").text());

                $("#total-price").val(total);
                console.log($("#total-price").val());

            }
            

            $(".increase").click(function () {
                let quantityElem = $(this).siblings(".quantity");
                let quantity = parseInt(quantityElem.val());
                {% comment %} let quantity = quantityElem.val() {% endcomment %}
                quantityElem.val(quantity + 1);
                updateTotal();
            });

            $(".decrease").click(function () {
                let quantityElem = $(this).siblings(".quantity");
                let quantity = parseInt(quantityElem.val());
                if (quantity > 1) {
                    quantityElem.val(quantity - 1);
                    updateTotal();
                }
            });
            console.log("Cart remove...")
            



            $(document).on('click', ".remove-cart", function () {
                var product_id = $(this).attr('data-product');
                var btn = $(this); 
                console.log("Adding product:", product_id);
                var url = ""; 

                url = "/ar/product/products/remove_cart";

                $.ajax({
                    url: url,
                    data: { product_id: product_id },
                    dataType: 'json',
                    success: function (res) {
                        console.log(res.message);
                        if (res.bool) {
                            alert("لم يتم حذف المنتج.");
                        } else {
                            {% comment %} alert("تم حذف المنتج."); {% endcomment %}
                            location.reload();
                            {% comment %} $("#cart-container").load("/ar/product/products/wishlist_partial"); {% endcomment %}

                        }
                    },
                    error: function (xhr, status, error) {
                        console.error("AJAX Error:", status, error);
                        alert("حدث خطأ في الحذف.");
                    }
                });
            });




            
            $(document).on('click', ".checkout-btn", function (e){
                e.preventDefault();
                console.log("*******");
                let totalPrice= $("#total-price").val();
                let addDicTextarea= $("#addDicTextarea").text();
                console.log(totalPrice);
                console.log(addDicTextarea);
                console.log("*******");

                url = "/ar/product/products/order_checkout";
                $.ajax({
                    url: url,
                    method: "POST",
                    data: {
                        totalPrice: totalPrice,
                        addDicTextarea: addDicTextarea,
                        csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
                     },
                    dataType: 'json',
                    success: function (res) {
                        console.log(res.message);
                        showAlert(res.state, res.message);
                        console.log(res.state, res.message)
                        location.reload();

                    },
                    error: function (xhr, status, error) {
                        console.log("AJAX Error:", status, error);
                        alert("حدث خطأ في الحذف.");
                    }
                });
            })
            updateTotal();
             // تحديث عند تحميل الصفحة
        });

        
        
        
    </script>

{% endblock %}

templates/product/order.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Orders {% endblock %} 

{% block content %}

  <section class="cart-wishlist-section" style="margin-bottom: 5rem;">
      <div class="container mt-3 mb-5">
        {% if orders_with_btn %}
          <div class="d-flex gap-2 justify-content-between align-items-center">
              <h2 class="text-center text-secondary"> طلباتك </h2>
          </div>
          {% for item in orders_with_btn %}
            <li>
              <strong>رقم الطلب:</strong> {{ item.order.code }}<br>
              <strong>الفاتورة:</strong> {{ item.order.value_bill }}<br>
              <strong>الوصف:</strong> {{ item.order.additional_description }}<br>
              <strong>حالة الشحن:</strong> {{ item.order.get_order_stats_display }}<br>
              <strong>حالة الدفع:</strong> {{ item.order.get_payment_stats_display }}<br>

              <strong>حالة الاستلام:</strong> {{ item.order.get_received_stats_display }}
              {% if item.show_btn %}
                <button class="btn btn-success btn-sm ml-2 received-btn" 
                data-product="{{item.order.id}}">{{ item.order.get_received_stats_display }}</button>
                <button class="btn btn-success btn-sm ml-2">الاتصال بالدعم</button>
              {% endif %}
              <br>

              <strong>محتويات السلة:</strong>
              <ul style="display: flex;min-width: 18rem;flex-wrap: wrap;gap: 2rem;align-content: flex-start;">
                {% for cart_item in item.cart_items %}
                  <li>
                  <a href="{% url 'Product_Detail' cart_item.product.id %}">
                    صورة المننتج:
                    <img class="cart-item-img" src="{{ cart_item.product.product_image.url }}" alt="بودي" >
                    <br>
                    المنتج: {{ cart_item.product.product_name }} <br>
                    الكمية: {{ cart_item.quantity }} <br>
                    السعر الإجمالي: {{ cart_item.total_price }} ريال
                  </a>
                  </li>
                {% empty %}
                  <li>لا توجد عناصر في الطلبيات</li>
                {% endfor %}
              </ul>

              <hr>
            </li>
          {% endfor %}        
        {% else %}
        <div class="d-flex gap-2 justify-content-between align-items-start flex-column mb-5">
              <h2 class="text-center text-secondary">  لا توجد طلبات  </h2>
              <a href="{%url 'index'%}" class="btn-primary-tow"> استمر بالتسوق </a>
        </div>    
        {% endif %}
      </div>
  </section>
{% endblock %}

{% block javascript %}
<script>
    document.addEventListener('DOMContentLoaded', function() {
      $(document).on('click', ".received-btn", function (e){
        e.preventDefault();
        console.log("*******");
        var order_id = $(this).attr('data-product');
        var btn = $(this); 
        console.log("order id:", order_id);
        var url = ""; 

        url = "/ar/product/products/mark_received";
        $.ajax({
            url: url,
            method: "POST",
            data: {
              order_id: order_id,
              csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val()
             },
            dataType: 'json',
            success: function (res) {
                console.log(res.message);
                showAlert(res.state, res.message);
                console.log(res.state, res.message)

                setTimeout(function () {
                  location.reload();
                }, 3000);
                
            },
            error: function (xhr, status, error) {
                console.log("AJAX Error:", status, error);
                alert("حدث خطأ في الحذف.");
            }
        });
      })
    })

</script>

{% endblock %}

templates/product/wishList.html
{% extends 'base.html' %}
{% load static %}
{% block title %} wishlist {% endblock %} 

{% block content %}
    <section class="cart-wishlist-section">
        <div class="container mt-3 mb-5">
            <div class="d-flex gap-2 justify-content-between align-items-center">
                <h2 class="text-center text-secondary"> مقتنياتك المميزة </h2>
            </div>
            <div class="row m-0" id="wishlist-container">
                {% include "product/wishlist_items.html" %}
            </div>
        </div>

    </section>
    {% include 'product/suggestionsProduct.html' %}

{% endblock %}
{% block javascript %}
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            
            console.log("wishlist")
            $(document).on('click', ".remove-wishlist", function(){
                var product_id = $(this).attr('data-product');
                var btn = $(this); 
            
                console.log("Adding product:", product_id);
                var url = ""; // تعيين الرابط حسب الشرط

                url = "/ar/product/products/remove_Wishlist";
            
                $.ajax({
                    // url: "single_cartItem_ar",
                    url: url,
                    data: { product_id: product_id }, // تأكد من أن المفتاح يتطابق مع الـ view
                    dataType: 'json',
                    success: function(res){
                        console.log(res);
                        console.log(res.message);
                    
                        {% comment %} 
                        if (res.bool) {
                            console.log(res.bool);
                            console.log(res.message);
                            location.reload();
                        } else {
                            console.log(res.bool);
                            console.log(res.message);
                            location.reload();

                        }  {% endcomment %}
                        if (res.bool) {
                            // تحديث قسم المفضلة فقط
                            alert("لم يتم حذف المنتج.");
                        } else {
                            $("#wishlist-container").load("/ar/product/products/wishlist_partial");
                        }
                        updateWishlistCount();
                    },
                    error: function(xhr, status, error) {
                        console.error("AJAX Error:", status, error);
                        alert("فشل الاتصال بالخادم! كود الخطأ: " + xhr.status);
                    }
                });
        
            });
            
            // Rate call function:-
            rate_conflict();
        }); 
    </script>
{% endblock %}